### ISSUE TITLE
Raw git shutting down.

### ISSUE THREAD

**Issue by tkreindler** [sidpagariya/MProjects#6]
Given the impending shutdown of raw git, it'd be awesome if you could move this useful tool onto github-pages or some other alternative.

**Comment by sidpagariya** [comment]
Thanks @tkreind! I am currently in the process of moving it, and I'll go ahead stick it into a different branch!

**Comment by sidpagariya** [comment]
Sorry for the late reply, but it's up and running on https://sidpagariya.github.io/MProjects/Schedule-maker/html/index.html
